context:
  version: "25.2.0"

package:
  name: "small_time"
  version: ${{ version }}

source:
  - git: https://github.com/thatstoasty/small-time.git
    rev: 3d16b2d4be7a0666725a4412ba827c9a122ec623

build:
  number: 0
  script:
    - mojo package src/small_time -o ${{ PREFIX }}/lib/mojo/small_time.mojopkg
requirements:
  host:
    - max =25.2
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo test test
    files:
      recipe:
        - test_small_time.mojo
        - test_time_delta.mojo
        - test_time_zone.mojo

about:
  homepage: https://github.com/thatstoasty/small-time
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: Apache-2.0
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE
  summary: Datetime library forked from morrow.mojo
  repository: https://github.com/thatstoasty/small-time

extra:
  maintainers:
    - thatstoasty
