context:
  version: "24.6.0"

package:
  name: "endia"
  version: ${{ version }}

source:
  - git: https://github.com/endia-ai/Endia.git
    rev: eeafbd1d1a519dbc63fd863c8922f37ec8f84a46

build:
  number: 0
  script:
    - mojo package endia -o ${{ PREFIX }}/lib/mojo/endia.mojopkg

requirements:
  host:
    - max =24.6
  run:
    - ${{ pin_compatible('max') }}

tests:
  - script:
      - if: unix
        then:
          - mojo run test.mojo
    requirements:
      run:
        - max =24.6
    files:
      recipe:
        - test.mojo

about:
  homepage: https://endia.vercel.app/
  license: Apache-2.0
  license_file: LICENSE
  summary: Dynamic Neural Networks in Mojo
  repository: https://github.com/endia-ai/Endia

extra:
  maintainers:
    - TilliFe
