name: Build and upload packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        label:
          - ubuntu-latest
          - macos-latest
          - magic_arm64_8core
    runs-on: ${{ matrix.label }}
    env:
      DATA_FILE: data/failed-compatibility-${{ matrix.label }}.json
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@8eaba7c61d661f73d558b0b477156b7b62667fa4 # v0.8.4
        with:
          pixi-version: v0.37.0

      - name: Configure git
        run: pixi run configure-git

      - name: Build packages
        shell: bash
        run: pixi run build-all --channel https://prefix.dev/modular-community --channel https://conda.modular.com/max
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
          RATTLER_BUILD_COLOR: always

      - name: Commit changes to failed-compatibility.json
        run: pixi run commit-changes ${{ env.DATA_FILE }}
        if: always()

      - name: Upload all packages
        shell: bash
        run: pixi run upload --channel modular-community
