name: Remove Incompatible Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # 9 AM PST

permissions:
  contents: write
  pull-requests: write

jobs:
  check-incompatible-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@8eaba7c61d661f73d558b0b477156b7b62667fa4 # v0.8.4
        with:
          pixi-version: v0.37.0

      - name: Configure git
        run: pixi run configure-git

      - name: Run compatibility check script
        run: pixi run remove-incompatible-packages
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
